import Testing
@testable import HexCore
import Foundation

@Suite("RobertaTokenizer")
struct RobertaTokenizerTests {

  // NOTE: These tests validate structural correctness of the tokenizer.
  // Cross-validation against Python-generated token IDs requires the real
  // roberta_vocab.json and roberta_merges.txt (generated by convert_gector_onnx.py).
  // Once those files are bundled, add exact ID matching tests.

  /// Build a minimal tokenizer for testing basic structure.
  /// Uses a tiny vocab + merge list that can encode simple ASCII text.
  private func makeMinimalTokenizer() throws -> RobertaTokenizer {
    // Minimal vocab: special tokens + individual byte-level chars + a few merges
    // GPT-2 byte encoding maps printable ASCII to themselves (! to ~, 0x21-0x7E)
    // Space (0x20) maps to Ġ (U+0120)

    var vocab = [String: Int]()
    vocab["<s>"] = 0
    vocab["<pad>"] = 1
    vocab["</s>"] = 2
    vocab["<unk>"] = 3

    // Add individual byte-level chars for printable ASCII
    var nextId = 4
    for byte in UInt8(0x21)...UInt8(0x7E) {
      let char = String(Character(Unicode.Scalar(byte)))
      vocab[char] = nextId
      nextId += 1
    }
    // Space byte (0x20) maps to Ġ (U+0120)
    vocab["\u{0120}"] = nextId
    nextId += 1

    // Add a few merged tokens
    vocab["\u{0120}w"] = nextId; nextId += 1  // Ġw
    vocab["\u{0120}wo"] = nextId; nextId += 1 // Ġwo
    vocab["he"] = nextId; nextId += 1
    vocab["ll"] = nextId; nextId += 1
    vocab["lo"] = nextId; nextId += 1
    vocab["hel"] = nextId; nextId += 1
    vocab["hell"] = nextId; nextId += 1
    vocab["hello"] = nextId; nextId += 1

    let vocabData = try JSONSerialization.data(withJSONObject: vocab)

    // Merges in priority order
    let merges = """
    h e
    l l
    l o
    he l
    hel l
    hell o
    \u{0120} w
    \u{0120}w o
    """
    let mergesData = merges.data(using: .utf8)!

    return try RobertaTokenizer(vocabData: vocabData, mergesData: mergesData)
  }

  @Test("Encode produces BOS and EOS framing")
  func encodeFraming() throws {
    let tokenizer = try makeMinimalTokenizer()
    let (tokenIds, _) = tokenizer.encode("hello")

    // First token should be BOS (0), last should be EOS (2)
    #expect(tokenIds.first == 0)
    #expect(tokenIds.last == 2)
    #expect(tokenIds.count >= 3) // BOS + at least 1 token + EOS
  }

  @Test("Word boundaries track word-to-token mapping")
  func wordBoundaries() throws {
    let tokenizer = try makeMinimalTokenizer()
    let (tokenIds, boundaries) = tokenizer.encode("hello")

    // Single word → 1 boundary
    #expect(boundaries.count == 1)
    #expect(boundaries[0].wordIndex == 0)
    #expect(boundaries[0].startTokenOffset == 1) // after BOS
    #expect(boundaries[0].endTokenOffset == tokenIds.count - 1) // before EOS
  }

  @Test("Multiple words produce multiple boundaries")
  func multipleWordBoundaries() throws {
    let tokenizer = try makeMinimalTokenizer()
    let (_, boundaries) = tokenizer.encode("a b")

    #expect(boundaries.count == 2)
    #expect(boundaries[0].wordIndex == 0)
    #expect(boundaries[1].wordIndex == 1)
    // Second word should start after first word ends
    #expect(boundaries[1].startTokenOffset >= boundaries[0].endTokenOffset)
  }

  @Test("Encode-decode round-trip preserves content")
  func roundTrip() throws {
    let tokenizer = try makeMinimalTokenizer()

    let input = "hello"
    let (tokenIds, _) = tokenizer.encode(input)
    let decoded = tokenizer.decode(tokenIds)
    #expect(decoded == input)
  }

  @Test("Empty string encodes to just BOS + EOS")
  func emptyString() throws {
    let tokenizer = try makeMinimalTokenizer()
    let (tokenIds, boundaries) = tokenizer.encode("")
    #expect(tokenIds == [0, 2]) // BOS, EOS
    #expect(boundaries.isEmpty)
  }

  @Test("Decode strips special tokens")
  func decodeStripsSpecial() throws {
    let tokenizer = try makeMinimalTokenizer()
    // Manually decode [BOS, some token, EOS] should not contain BOS/EOS text
    let decoded = tokenizer.decode([0, 2])
    #expect(decoded == "")
  }

  @Test("Unknown characters produce UNK tokens")
  func unknownChars() throws {
    let tokenizer = try makeMinimalTokenizer()
    // Our minimal tokenizer only has printable ASCII
    // Encoding a character outside that range should still work (via byte encoding)
    let (tokenIds, _) = tokenizer.encode("a")
    #expect(tokenIds.count == 3) // BOS + "a" + EOS
  }
}
